# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: redhat-marketplace-operator
replicaCount: 1
namespace: openshift-redhat-marketplace
image: quay.io/rh-marketplace/redhat-marketplace-operator:latest
reporterImage: quay.io/rh-marketplace/redhat-marketplace-reporter:latest
metricStateImage: quay.io/rh-marketplace/redhat-marketplace-metric-state:latest
authCheckImage: quay.io/rh-marketplace/redhat-marketplace-authcheck:latest
kubeRbacProxyImage: registry.redhat.io/openshift4/ose-kube-rbac-proxy:latest
pullPolicy: Always
watchNamespace: '' # watch all namespaces
serviceAccountName: redhat-marketplace-operator
devpostfix: ''
imagePullSecret: ''
env:
  - name: RELATED_IMAGE_RHM_RRS3_DEPLOYMENT
    value: quay.io/razee/remoteresources3:0.6.2
  - name: RELATED_IMAGE_RHM_WATCH_KEEPER_DEPLOYMENT
    value: quay.io/razee/watch-keeper:0.6.6
  - name: RELATED_IMAGE_PROMETHEUS
    value: registry.redhat.io/openshift4/ose-prometheus:v4.5
  - name: RELATED_IMAGE_OAUTH_PROXY
    value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.5
  - name: RELATED_IMAGE_PROMETHEUS_OPERATOR
    value: registry.redhat.io/openshift4/ose-prometheus-operator:v4.5
  - name: RELATED_IMAGE_CONFIGMAP_RELOADER
    value: registry.redhat.io/openshift4/ose-configmap-reloader:v4.5
  - name: RELATED_IMAGE_PROMETHEUS_CONFIGMAP_RELOADER
    value: registry.redhat.io/openshift4/ose-prometheus-config-reloader:v4.5
  - name: RELATED_IMAGE_KUBE_RBAC
    value: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.5
  - name: IBMCATALOGSOURCE
    value: 'true'
  - name: PATH_TO_KUBE_PROXY_TOKEN
    value: /etc/auth-service-account/token
roles:
  - name: redhat-marketplace-operator
    serviceAccountName: redhat-marketplace-operator
    type: ClusterRole
    rules:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs: ['get', 'list', 'watch']
      - nonResourceURLs:
          - '*'
        verbs: ['get', 'list', 'watch']
      - apiGroups:
          - rbac.authorization.k8s.io
        resources:
          - clusterroles
        resourceNames:
          - razeedeploy-admin-cr
          - redhat-marketplace-razeedeploy
        verbs:
          - get
          - list
          - delete
      - apiGroups:
          - ''
        resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - persistentvolumes
          - events
          - configmaps
          - secrets
          - namespaces
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ''
        resources:
          - nodes
        verbs:
          - get
          - list
          - watch
          - patch
          - update
      - apiGroups: ['batch', 'extensions']
        resources: ['jobs']
        verbs: ['get', 'list', 'watch']
      - apiGroups:
          - apps
        resources:
          - deployments
          - statefulsets
          - replicasets
          - daemonsets
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - apps
        resourceNames:
          - redhat-marketplace-operator
        resources:
          - deployments/finalizers
        verbs:
          - update
      - apiGroups:
          - storage.k8s.io
        resources:
          - storageclasses
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - monitoring.coreos.com
        resources:
          - servicemonitors
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - monitoring.coreos.com
        resources:
          - prometheuses
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - operators.coreos.com
        resources:
          - subscriptions
          - clusterserviceversions
        verbs:
          - get
          - list
          - update
          - watch
          - delete
      - apiGroups:
          - operators.coreos.com
        resources:
          - operatorsources
          - catalogsources
        verbs:
          - get
          - list
          - watch
          - create
      - apiGroups:
          - operators.coreos.com
        resourceNames:
          - redhat-marketplace
        resources:
          - operatorsources
        verbs:
          - get
          - delete
          - patch
          - update
      - apiGroups:
          - operators.coreos.com
        resourceNames:
          - ibm-operator-catalog
          - opencloud-operators
        resources:
          - catalogsources
        verbs:
          - get
          - delete
          - patch
          - update
      - apiGroups:
          - operators.coreos.com
        resources:
          - operatorgroups
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - deploy.razee.io
        resources:
          - remoteresourcess3
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
      - apiGroups:
          - config.openshift.io
        resources:
          - consoles
          - infrastructures
          - clusterversions
        verbs:
          - get
          - list
          - patch
          - update
      - apiGroups:
          - marketplace.redhat.com
        resources:
          - '*'
          - meterdefinitions
          - razeedeployments
          - meterbases
          - marketplaceconfigs
          - remoteresources3s
        verbs:
          - '*'
      - apiGroups:
          - ''
        resources:
          - secrets
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        resourceNames:
          - rhm-cos-reader-key
          - watch-keeper-secret
      - apiGroups:
          - ''
        resources:
          - configmaps
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        resourceNames:
          - watch-keeper-config
          - watch-keeper-limit-poll
          - watch-keeper-non-namespaced
          - razee-cluster-metadata
      - apiGroups:
          - authentication.k8s.io
        resources:
          - tokenreviews
        verbs:
          - create
      - apiGroups:
          - authorization.k8s.io
        resources:
          - subjectaccessreviews
        verbs:
          - create
      # reporter: gives access to query prometheus
      - nonResourceURLs:
          - /api/v1/query
          - /api/v1/query_range
        verbs:
          - get
          - create
  # redhat-marketplace-remoteresources3deployment ClusterRole
  - name: redhat-marketplace-remoteresources3deployment
    serviceAccountName: redhat-marketplace-remoteresources3deployment
    type: ClusterRole
    rules:
      - apiGroups:
          - operators.coreos.com
          - marketplace.redhat.com
        resources:
          - '*'
        verbs:
          - '*'
      - nonResourceURLs:
          - '*'
        verbs: ['get', 'list', 'watch']
  # redhat-marketplace-remoteresources3deployment ClusterRole
  - name: redhat-marketplace-remoteresources3deployment
    serviceAccountName: redhat-marketplace-remoteresources3deployment
    type: Role
    rules:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - '*'
  - name: redhat-marketplace-prometheus-operator
    serviceAccountName: redhat-marketplace-prometheus-operator
    type: ClusterRole
    rules:
      - apiGroups:
          - apiextensions.k8s.io
        resources:
          - customresourcedefinitions
        verbs:
          - create
      - apiGroups:
          - apiextensions.k8s.io
        resourceNames:
          - alertmanagers.monitoring.coreos.com
          - podmonitors.monitoring.coreos.com
          - prometheuses.monitoring.coreos.com
          - prometheusrules.monitoring.coreos.com
          - servicemonitors.monitoring.coreos.com
        resources:
          - customresourcedefinitions
        verbs:
          - get
          - update
      - apiGroups:
          - monitoring.coreos.com
        resources:
          - alertmanagers
          - prometheuses
          - prometheuses/finalizers
          - alertmanagers/finalizers
          - servicemonitors
          - podmonitors
          - prometheusrules
          - '*'
        verbs:
          - '*'
      - apiGroups:
          - apps
        resources:
          - statefulsets
        verbs:
          - '*'
      - apiGroups:
          - ''
        resources:
          - configmaps
          - secrets
        verbs:
          - '*'
      - apiGroups:
          - ''
        resources:
          - pods
        verbs:
          - list
          - delete
      - apiGroups:
          - ''
        resources:
          - services
          - services/finalizers
          - endpoints
        verbs:
          - get
          - create
          - update
          - delete
      - apiGroups:
          - ''
        resources:
          - nodes
        verbs:
          - list
          - watch
      - apiGroups:
          - ''
        resources:
          - namespaces
        verbs:
          - get
          - list
          - watch
  - name: redhat-marketplace-prometheus
    serviceAccountName: redhat-marketplace-prometheus
    type: ClusterRole
    rules:
      - apiGroups:
          - ''
        resources:
          - nodes/metrics
        verbs:
          - get
      - nonResourceURLs:
          - /metrics
        verbs:
          - get
      - apiGroups:
          - authentication.k8s.io
        resources:
          - tokenreviews
        verbs:
          - create
      - apiGroups:
          - authorization.k8s.io
        resources:
          - subjectaccessreviews
        verbs:
          - create
      - apiGroups:
          - ''
        resources:
          - namespaces
        verbs:
          - get
      - apiGroups:
          - ''
        resources:
          - services
          - endpoints
          - pods
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - monitoring.coreos.com
        resources:
          - '*'
        verbs:
          - get
          - list
          - patch
          - update
          - watch
  - name: redhat-marketplace-prometheus
    serviceAccountName: redhat-marketplace-prometheus
    type: Role
    rules:
      - apiGroups:
          - ''
        resources:
          - configmaps
        verbs:
          - get
  # redhat-marketplace-watch-keeper ClusterRole
  - name: redhat-marketplace-watch-keeper
    serviceAccountName: redhat-marketplace-watch-keeper
    type: ClusterRole
    rules:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs: ['get', 'list', 'watch']
      - nonResourceURLs:
          - '*'
        verbs: ['get', 'list', 'watch']
  # redhat-marketplace-watch-keeper ClusterRole
  - name: redhat-marketplace-reporter
    namespace: openshift-config
    serviceAccountName: redhat-marketplace-operator
    type: Role
    rules:
      - apiGroups: ['']
        #
        # at the HTTP level, the name of the resource for accessing Secret
        # objects is "secrets"
        resources: ['secrets']
        verbs: ['get', 'watch', 'list']
        resourceNames:
          - pull-secret

  # rhm-operator Role
  - name: redhat-marketplace-operator
    serviceAccountName: redhat-marketplace-operator
    type: Role
    rules:
      - apiGroups:
          - deploy.razee.io
        resources:
          - '*'
          - remoteresourcess3
          - remoteresources
        verbs:
          - create
          - delete
          - get
          - list
          - update
          - patch
          - watch
      - apiGroups:
          - ''
        resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - operators.coreos.com
        resources:
          - subscriptions
        verbs:
          - get
          - list
          - watch
          - create
          - delete
          - patch
          - watch
          - update
      - apiGroups:
          - batch
          - extensions
        resources:
          - jobs
        verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
      - apiGroups:
          - apps
        resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - apps
        resourceNames:
          - redhat-marketplace-operator
        resources:
          - deployments/finalizers
        verbs:
          - update
      - apiGroups:
          - monitoring.coreos.com
        resources:
          - '*'
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - ''
        resources:
          - serviceaccounts
        verbs:
          - create
          - delete
          - get
          - list
          - update
          - patch
          - watch
        resourceNames:
          - razeedeploy-sa
          - watch-keeper-sa
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
