apiVersion: marketplace.redhat.com/v1alpha1
kind: MarketplaceConfig
metadata:
  name: marketplaceconfig
spec:
  rhmAccountID: example-userid
  clusterUUID: example-clusterUUID
  deploySecretName: rhm-operator-secret
  installIBMCatalogSource: false
